#
#
#
#
#

#Languages:
# - pl
# - en
lang: "en"

#Databases:
# - MYSQL
# - FILE
databaseType: FILE
databaseConnection:
  url: "jdbc:mysql://localhost:3306/nazwa_bazy"
  user: "root"
  password: "haslo"
