#
#
#
#
#

#Languages:
# - pl
# - en
lang: "en"

#Databases:
# - MYSQL
# - FILE
databaseType: MYSQL
databaseConnection:
  host: "localhost"
  user: "kotek"
  password: "kotek"
  name: "db"
  port: "3306"
  #forceURL: "jdbc:mysql://localhost:3306/db?useSSL=false&allowPublicKeyRetrieval=true"